version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-own-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: myroot
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb

  app:
    build: .
    container_name: my-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      DB_URL: mongodb://myroot:password@mongodb:27017/mydb
